# Generated by Django 2.0.5 on 2018-06-28 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='website',
        ),
    ]
