# Generated by Django 2.0.5 on 2018-07-08 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20180701_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cust_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='crm.Customer'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cust_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='crm.Customer'),
        ),
    ]
